
name: Run TAF and publish results

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.R'
      - 'boot/initial/data/**'
      - 'boot/DATA.bib'
      - 'boot/SOFTWARE.bib'
      - .github/workflows/taf.yml

jobs:
  taf-run:
    uses: ices-tools-prod/workflows/.github/workflows/taf-run.yml@main
    with:
      r-version: "release"
      timeout-minutes: 10
